# 9menu.1x
# Autogenerated from man page /usr/share/man/man1/9menu.1x.gz
complete -c '9menu.1x' -o bg -d 'Set the background color to R background-color '
complete -c '9menu.1x' -o display -d 'Use the X display R displayname , instead of the default display'
complete -c '9menu.1x' -o file -d 'Read items to display from R filename , in addition to any other command line…'
complete -c '9menu.1x' -o fg -d 'Set the foreground color to R foreground-color '
complete -c '9menu.1x' -o font -d 'Use the font R fname , instead of one of the default fonts built into R 9wm '
complete -c '9menu.1x' -o geometry -d 'Use  geom (a geometry in standard X format) as the geometry of the menu'
complete -c '9menu.1x' -o iconic -d 'Start up in the iconified state'
complete -c '9menu.1x' -o label -d 'Change both the window and icon labels of the window to R name '
complete -c '9menu.1x' -o path -d 'Append the current directory to the command search path'
complete -c '9menu.1x' -o popdown -d 'Once an item is selected, the menu window automatically iconifies itself'
complete -c '9menu.1x' -o popup -d 'Act like a pop-up menu.  Once a menu item is selected,  9menu exits'
complete -c '9menu.1x' -o shell -d 'Use  prog as the shell to run commands, instead of  /bin/sh '
complete -c '9menu.1x' -o teleport -d 'Move the menu to where the mouse is when the menu is uniconified'
complete -c '9menu.1x' -o version -d 'This option prints the version of  9menu on the standard output, and then exi…'
complete -c '9menu.1x' -o warp -d 'Warp the mouse to the menu when the menu is uniconified'

