# clp
# Autogenerated from man page /usr/share/man/man1/clp.1.gz
complete -c clp -l list-overrides -d 'HP -t, --override-colortheme {filetype}'
complete -c clp -s l -d 'See below'
complete -c clp -s t -l override-filetype -d 'Force a language\'s syntax for highlighting the file'
complete -c clp -l override-colortheme -d 'Override the color theme defined in clprc. lua '
complete -c clp -s h -l highlight-line -d 'Highlight a non-blank line FILES Upon startup will source the first clprc'

