# compel
# Autogenerated from man page /usr/share/man/man1/compel.1.gz
complete -c compel -s f -l file -d 'Path to the binary file, FILE, which compel must turn into a header'
complete -c compel -s o -l output -d 'Path to the header file, FILE, where compel must write the resulting header'
complete -c compel -s p -l prefix -d 'Specify prefix for var names'
complete -c compel -s l -l log-level -d 'Default log level of compel'
complete -c compel -s h -l help -d 'Prints usage and exits'
complete -c compel -s V -l version -d 'Prints version number of compel'

