# containers-storage-get-image-data
# Autogenerated from man page /usr/share/man/man1/containers-storage-get-image-data.1.gz
complete -c containers-storage-get-image-data -s f -l file -d 'Write the data to a file instead of stdout'

