# containers-storage-remove-names
# Autogenerated from man page /usr/share/man/man1/containers-storage-remove-names.1.gz
complete -c containers-storage-remove-names -s n -l name -d 'Specifies a name to remove from the layer, image, or container'

