# disdvi
# Autogenerated from man page /usr/share/man/man1/disdvi.1.gz
complete -c disdvi -s p -d 'Handle ASCII pTeX dvi file'
complete -c disdvi -s u -d 'Handle upTeX dvi file'
complete -c disdvi -o Eenc -d 'Set output multibyte encoding'
complete -c disdvi -s x -d 'Handle XeTeX xdv file'
complete -c disdvi -s h -d 'Show a help massage and exit successfully'

