# dragon-drop
# Autogenerated from man page /usr/share/man/man1/dragon-drop.1.gz
complete -c dragon-drop -s x -l and-exit -d 'exit after a single completed drop'
complete -c dragon-drop -s t -l target -d 'act as a target instead of source'
complete -c dragon-drop -s k -l keep -d 'with --target, keep files to drag out'
complete -c dragon-drop -s p -l print-path -d 'with --target, print file paths instead of URIs'
complete -c dragon-drop -s a -l all -d 'drag all files at once'
complete -c dragon-drop -s A -l all-compact -d 'drag all files at once, only displaying the number of files'
complete -c dragon-drop -s i -l icon-only -d 'only show icons in drag-and-drop windows'
complete -c dragon-drop -s T -l on-top -d 'make window always-on-top'
complete -c dragon-drop -s I -l stdin -d 'read filenames from stdin'
complete -c dragon-drop -s s -l thumb-size -d 'set thumbnail size (default 96)'
complete -c dragon-drop -s v -l verbose -d 'be verbose'
complete -c dragon-drop -l help -d 'show help'
complete -c dragon-drop -l version -d 'show version details'

