# ii
# Autogenerated from man page /usr/local/man/man1/ii.1
complete -c ii -s s -d 'server/host to connect to, for example: irc. freenode. net'
complete -c ii -s p -d 'lets you override the default port (6667)'
complete -c ii -s u -d 'connect to a UNIX domain socket instead of directly to a server'
complete -c ii -s i -d 'lets you override the default irc path (~/irc)'
complete -c ii -s n -d 'lets you override the default nick ($USER)'
complete -c ii -s f -d 'lets you specify your real name associated with your nick'
complete -c ii -s k -d 'lets you specify an environment variable that contains your IRC password, e'

