# jabswitch-jdk20
# Autogenerated from man page /usr/share/man/man1/jabswitch-jdk20.1.gz
complete -c jabswitch-jdk20 -o enable
complete -c jabswitch-jdk20 -o disable -d Bridge
complete -c jabswitch-jdk20 -o version -d 'for the jabswitch command'
complete -c jabswitch-jdk20 -s '?' -d 'jabswitch command.  DESCRIPTION'

