# jhsdb-jdk20
# Autogenerated from man page /usr/share/man/man1/jhsdb-jdk20.1.gz
complete -c jhsdb-jdk20 -l serverid -d 'An optional unique ID for this debug server'
complete -c jhsdb-jdk20 -l rmiport -d 'Sets the port number to which the RMI connector is bound'
complete -c jhsdb-jdk20 -l registryport -d 'Sets the RMI registry port'
complete -c jhsdb-jdk20 -l hostname -d 'Sets the hostname the RMI connector is bound'
complete -c jhsdb-jdk20 -l flags -d 'Prints the VM flags'
complete -c jhsdb-jdk20 -l sysprops -d 'Prints the Java system properties'
complete -c jhsdb-jdk20 -l heap -d 'Prints the java heap summary'
complete -c jhsdb-jdk20 -l binaryheap -d 'Dumps the java heap in hprof binary format'
complete -c jhsdb-jdk20 -l dumpfile -d 'The name of the dumpfile'
complete -c jhsdb-jdk20 -l histo -d 'Prints the histogram of java object heap'
complete -c jhsdb-jdk20 -l clstats -d 'Prints the class loader statistics'
complete -c jhsdb-jdk20 -l finalizerinfo -d 'Prints the information on objects awaiting finalization'
complete -c jhsdb-jdk20 -l locks -d 'Prints the java. util. concurrent locks information'
complete -c jhsdb-jdk20 -l mixed -d 'Attempts to print both java and native frames if the platform allows it'
complete -c jhsdb-jdk20 -l all -d 'Prints all performance counters'

