# jlink-jdk20
# Autogenerated from man page /usr/share/man/man1/jlink-jdk20.1.gz
complete -c jlink-jdk20 -l add-modules -d 'Adds the named modules, mod, to the default set of root modules'
complete -c jlink-jdk20 -l bind-services -d 'Link service provider modules and their dependencies'
complete -c jlink-jdk20 -s c -l compress -d 'Enable compression of resources:'
complete -c jlink-jdk20 -l disable-plugin -d 'Disables the specified plug-in'
complete -c jlink-jdk20 -l endian -d 'Specifies the byte order of the generated image'
complete -c jlink-jdk20 -s h -l help -d 'Prints the help message'
complete -c jlink-jdk20 -l ignore-signing-information -d 'Suppresses a fatal error when signed modular JARs are linked in the runtime i…'
complete -c jlink-jdk20 -l launcher -l launcher -d 'Specifies the launcher command name for the module or the command name for th…'
complete -c jlink-jdk20 -l limit-modules -d 'Limits the universe of observable modules to those in the transitive closure …'
complete -c jlink-jdk20 -l list-plugins -d 'Lists available plug-ins, which you can access through command-line options; …'
complete -c jlink-jdk20 -s p -l module-path -d 'Specifies the module path'
complete -c jlink-jdk20 -l no-header-files -d 'Excludes header files'
complete -c jlink-jdk20 -l no-man-pages -d 'Excludes man pages'
complete -c jlink-jdk20 -l output -d 'Specifies the location of the generated runtime image'
complete -c jlink-jdk20 -l save-opts -d 'Saves jlink options in the specified file'
complete -c jlink-jdk20 -l suggest-providers -d 'Suggest providers that implement the given service types from the module path'
complete -c jlink-jdk20 -l version -d 'Prints version information'
complete -c jlink-jdk20 -l include-locales
complete -c jlink-jdk20 -l order-resources
complete -c jlink-jdk20 -l strip-debug
complete -c jlink-jdk20 -l generate-cds-archive

