# jmap-jdk20
# Autogenerated from man page /usr/share/man/man1/jmap-jdk20.1.gz
complete -c jmap-jdk20 -o clstats -d 'Connects to a running process and prints class loader statistics of Java heap'
complete -c jmap-jdk20 -o finalizerinfo -d 'Connects to a running process and prints information on objects awaiting fina…'
complete -c jmap-jdk20 -o histo -d 'Connects to a running process and prints a histogram of the Java object heap'
complete -c jmap-jdk20 -o dump:dump_options -d 'Connects to a running process and dumps the Java heap'

