# jstack-jdk20
# Autogenerated from man page /usr/share/man/man1/jstack-jdk20.1.gz
complete -c jstack-jdk20 -s l -d 'The long listing option prints additional information about locks'
complete -c jstack-jdk20 -s h -o help -d 'Prints a help message'

