# jstatd-jdk20
# Autogenerated from man page /usr/share/man/man1/jstatd-jdk20.1.gz
complete -c jstatd-jdk20 -o nr -d 'OPTIONS FOR THE JSTATD COMMAND'
complete -c jstatd-jdk20 -s p -d 'This option sets the port number where the RMI registry is expected to be fou…'
complete -c jstatd-jdk20 -s r -d 'This option sets the port number to which the RMI connector is bound'
complete -c jstatd-jdk20 -s n -d 'This option sets the name to which the remote RMI object is bound in the RMI …'
complete -c jstatd-jdk20 -o Joption -d 'This option passes a Java option to the JVM, where the option is one of those…'

