# kinit-jdk20
# Autogenerated from man page /usr/share/man/man1/kinit-jdk20.1.gz
complete -c kinit-jdk20 -s A -d 'Doesn[aq]t include addresses'
complete -c kinit-jdk20 -s f -d 'Issues a forwardable ticket'
complete -c kinit-jdk20 -s p -d 'Issues a proxiable ticket'
complete -c kinit-jdk20 -s c -d 'The cache name (for example, FILE:D:[rs]temp[rs]mykrb5cc)'
complete -c kinit-jdk20 -s l -d 'Sets the lifetime of a ticket'
complete -c kinit-jdk20 -s r -d 'Sets the total lifetime that a ticket can be renewed'
complete -c kinit-jdk20 -s R -d 'Renews a ticket'
complete -c kinit-jdk20 -s k -d 'Uses keytab'
complete -c kinit-jdk20 -s t -d 'The keytab name (for example, D:[rs]winnt[rs]profiles[rs]duke[rs]krb5'

