# klist-jdk20
# Autogenerated from man page /usr/share/man/man1/klist-jdk20.1.gz
complete -c klist-jdk20 -s c -d 'Specifies that the credential cache is to be listed'
complete -c klist-jdk20 -s f -d 'Show credential flags'
complete -c klist-jdk20 -s e -d 'Show the encryption type'
complete -c klist-jdk20 -s a -d 'Show addresses'
complete -c klist-jdk20 -s n -d 'If the -a option is specified, don[aq]t reverse resolve addresses'
complete -c klist-jdk20 -s k -d 'Specifies that key tab is to be listed.  List the keytab entries'
complete -c klist-jdk20 -s t -d 'Show keytab entry timestamps'
complete -c klist-jdk20 -s K -d 'Show keytab entry DES keys'
complete -c klist-jdk20 -o help -d 'Displays instructions.  EXAMPLES'

