# ktab-jdk20
# Autogenerated from man page /usr/share/man/man1/ktab-jdk20.1.gz
complete -c ktab-jdk20 -s l -d 'Lists the keytab name and entries'
complete -c ktab-jdk20 -s a -s n -s s -s f -d 'Adds new key entries to the keytab for the given principal name with an optio…'
complete -c ktab-jdk20 -s d -s e -d 'Deletes key entries from the keytab for the specified principal'
complete -c ktab-jdk20 -o help -d 'Displays instructions.  COMMON OPTIONS'
complete -c ktab-jdk20 -s k -d 'Specifies the keytab name and path with the FILE: prefix'

