# lchat
# Autogenerated from man page /usr/local/man/man1/lchat.1
complete -c lchat -s a -d 'Turn off the bell on external line input'
complete -c lchat -s e -d 'Allow to enter empty lines'
complete -c lchat -s h -d 'Shows usage text'
complete -c lchat -s n -d 'Shows lines of chat history at startup'
complete -c lchat -s p -d 'Use prompt as prompt for the input line'
complete -c lchat -s t -d 'Use title as title for the terminal window'
complete -c lchat -s i -d 'Use path of in as in-file.  Default is \'in\'.  This overrides directory'
complete -c lchat -s o -d 'Use path of out as out-file.  Default is \'out\'.  This overrides directory'

