# openslide-quickhash1sum
# Autogenerated from man page /usr/share/man/man1/openslide-quickhash1sum.1.gz
complete -c openslide-quickhash1sum -l help -d 'Display usage summary'
complete -c openslide-quickhash1sum -l version -d 'Display version and copyright information'

