# openslide-write-png
# Autogenerated from man page /usr/share/man/man1/openslide-write-png.1.gz
complete -c openslide-write-png -l help -d 'Display usage summary'
complete -c openslide-write-png -l version -d 'Display version and copyright information'

