# openslide-show-properties
# Autogenerated from man page /usr/share/man/man1/openslide-show-properties.1.gz
complete -c openslide-show-properties -l help -d 'Display usage summary'
complete -c openslide-show-properties -l version -d 'Display version and copyright information'

