# serialver-jdk20
# Autogenerated from man page /usr/share/man/man1/serialver-jdk20.1.gz
complete -c serialver-jdk20 -o classpath -d 'Sets the search path for application classes and resources'
complete -c serialver-jdk20 -o Joption -d 'Passes the specified option to the Java Virtual Machine, where option is one …'
complete -c serialver-jdk20 -o 'J-Djava.security.manager' -d 'When necessary, a security policy can be specified with the following option:'
complete -c serialver-jdk20 -o 'J-Djava.security.policy'

