# sic
# Autogenerated from man page /usr/local/man/man1/sic.1
complete -c sic -s h -d 'Overrides the default host (irc. oftc. net)'
complete -c sic -s p -d 'Overrides the default port (6667)'
complete -c sic -s n -d 'Override the default nick ($USER)'
complete -c sic -s k -d 'Specifies the PASS connection password'
complete -c sic -s v -d 'Prints version information to stderr, then exits COMMANDS'

