# slock
# Autogenerated from man page /usr/local/man/man1/slock.1
complete -c slock -s v -d 'Print version information to stdout and exit'
complete -c slock -s m -d 'Overrides default slock lock message'

