# stagit
# Autogenerated from man page /usr/local/man/man1/stagit.1
complete -c stagit -s c -d 'Cache the entries of the log page up to the point of the last commit'
complete -c stagit -s l -d 'Write a maximum number of commits to the log. html file only'
complete -c stagit -s u -d 'Base URL to make links in the Atom feeds absolute.  For example: "https://git'

