# svkbd
# Autogenerated from man page /usr/local/man/man1/svkbd.1
complete -c svkbd -s D -d 'Debug mode; output verbosely to stderr'
complete -c svkbd -s d -d 'Set the _NET_WM_WINDOW_TYPE_DOCK property to hint windowmanagers it is dockab…'
complete -c svkbd -o fn -d 'Defines the font or font set used.  e. g'
complete -c svkbd -s g -d 'Adjust the initial window position or size as specified by the standard X11 g…'
complete -c svkbd -s h -d 'Show the usage information'
complete -c svkbd -s H -d 'Affects the vertical space taken by the keyboard'
complete -c svkbd -s l -d 'Comma separated list of layers to enable (by name)'
complete -c svkbd -s n -d 'Do not simulate key presses for X'
complete -c svkbd -s R -d 'Disable press-on-release'
complete -c svkbd -s s -d 'The layer to show on program start-up (by name)'
complete -c svkbd -s O -d 'Disable overlay functionality'
complete -c svkbd -s o -d 'Print pressed keys to standard output'
complete -c svkbd -s v -d 'Show the version information'

