# vimb
# Autogenerated from man page /usr/local/man/man1/vimb.1
complete -c vimb -s C -l cmd -d 'Run CMD as ex command line right before the first page is loaded'
complete -c vimb -s c -l config -d 'Use custom configuration given as FILE'
complete -c vimb -s e -l embed -d 'WINID of an XEmbed-aware application, that Vimb will use as its parent'
complete -c vimb -s i -l incognito -d 'Start an instance with user data read-only (see FILES section)'
complete -c vimb -s h -l help -d 'Show help options'
complete -c vimb -s p -l profile -d 'Create or open specified configuration profile'
complete -c vimb -s v -l version -d 'Print build and version information and then quit'
complete -c vimb -l no-maximize -d 'Do no attempt to maximize window'
complete -c vimb -l bug-info -d 'Prints information about used libraries for bug reports and then quit'

