# xmlstarlet
# Autogenerated from man page /usr/share/man/man1/xmlstarlet.1.gz
complete -c xmlstarlet -l version -d 'Display the version of xmlstarlet'
complete -c xmlstarlet -l help -d 'Display help'

